import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import PostsRoute from "./posts";
import ProfileRoute from "./profile";
import SlidersRoute from "./sliders";
import PopUpsRoute from "./popUps";
import CompetitionRoute from "./competitions";
import ComplaintRoute from "./complaints";
import DashboardRoute from "./dashboard";
import ComplaintsCategoryRoute from "./complaintsCategory";
import AuthRoute from "./auth";
import UsersAdmin from "./users";
import voteRoute from "./votes";
import notificationRoutes from './Notification';
import { Router } from "express";
const route = Router();
route.use("/auth", AuthRoute);
route.use(authenticated, authorizeRoles("admin"));
route.use("/profile", ProfileRoute);
route.use("/dashboard", DashboardRoute);
route.use("/users", UsersAdmin);
route.use("/votes", voteRoute);
route.use("/posts", PostsRoute);
route.use("/popups", PopUpsRoute);
route.use("/sliders", SlidersRoute);
route.use("/complaints/category", ComplaintsCategoryRoute);
route.use("/complaints", ComplaintRoute);
route.use("/competitions", CompetitionRoute);
route.use("/notifications", notificationRoutes);

export default route;
